Repository mattermost/mattermost-operator, pull requests merged in 2020-10, with the labels that each got.

#183 DOPS-216: Add MM_INSTALL_TYPE=kubernetes
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_test.go
Labels: 3: Reviews Complete, kind/cleanup, release-note-none

#186 expose metrics port for prometheus operator
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_test.go
Labels: 3: Reviews Complete, kind/feature, release-note

#187 Bump default Mattermost version to 5.28.0
  apis/mattermost/v1alpha1/clusterinstallation_utils.go
Labels: 2: Dev Review, release-note
