Repository mattermost/mattermost-operator, pull requests merged in 2020-06, with the labels that each got.

#146 Update e2e kind cluster to user kind 0.8.1 and Kubernetes 1.16.9
  .circleci/config.yml
  test/kind-config.yaml
Labels: 3: Reviews Complete, kind/feature, priority/important-soon, release-note

#149 Bump default Mattermost version
  pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Labels: 2: Dev Review, 2: Infra Review, release-note

#151 Handle negative Mattermost replicas
  pkg/apis/mattermost/v1alpha1/clusterinstallation_sizes.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Labels: 3: Reviews Complete, kind/cleanup, release-note

#152 Handle negative replica count on final check
  pkg/controller/clusterinstallation/utils.go
Labels: 2: Dev Review, 2: Infra Review, release-note

#153 Update tests to use k8s 1.17
  .circleci/config.yml
  Makefile
  build/Dockerfile
  test/kind-config.yaml
Labels: 2: Infra Review, kind/cleanup, release-note

#154 update checker: remove probes from the job
  pkg/controller/clusterinstallation/mattermost.go
Labels: 3: Reviews Complete, kind/cleanup, release-note
