Repository mattermost/mattermost-operator, pull requests merged in 2020-12, with the labels that each got.

#201 Disable DB setup job until we can do it while respecting custom configuration
  controllers/mattermost/clusterinstallation/mattermost.go
  controllers/mattermost/clusterinstallation/mattermost_test.go
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_test.go
Labels: 3: Reviews Complete, release-note

#202 [MM-29303] add release script
  README.md
  scripts/release.sh
Labels: kind/feature, release-note

#200 MM-30827 - Adjust beta types, generate new clients and CRD
  .circleci/config.yml
  Makefile
  PROJECT
  apis/mattermost/v1alpha1/clusterinstallation_sizes.go
  apis/mattermost/v1alpha1/clusterinstallation_test.go
  apis/mattermost/v1beta1/db_util.go
  apis/mattermost/v1beta1/file_store_util.go
  apis/mattermost/v1beta1/groupversion_info.go
  apis/mattermost/v1beta1/mattermost_sizes.go
  apis/mattermost/v1beta1/mattermost_test.go
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/mattermost_utils.go
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  apis/mattermost/v1beta1/zz_generated.openapi.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  pkg/client/v1beta1/clientset/versioned/clientset.go
  pkg/client/v1beta1/clientset/versioned/doc.go
  pkg/client/v1beta1/clientset/versioned/fake/clientset_generated.go
  pkg/client/v1beta1/clientset/versioned/fake/doc.go
  pkg/client/v1beta1/clientset/versioned/fake/register.go
  pkg/client/v1beta1/clientset/versioned/scheme/doc.go
  pkg/client/v1beta1/clientset/versioned/scheme/register.go
  pkg/client/v1beta1/clientset/versioned/typed/mattermost/v1beta1/doc.go
  pkg/client/v1beta1/clientset/versioned/typed/mattermost/v1beta1/fake/doc.go
  pkg/client/v1beta1/clientset/versioned/typed/mattermost/v1beta1/fake/fake_mattermost.go
  pkg/client/v1beta1/clientset/versioned/typed/mattermost/v1beta1/fake/fake_mattermost_client.go
  pkg/client/v1beta1/clientset/versioned/typed/mattermost/v1beta1/generated_expansion.go
  pkg/client/v1beta1/clientset/versioned/typed/mattermost/v1beta1/mattermost.go
  pkg/client/v1beta1/clientset/versioned/typed/mattermost/v1beta1/mattermost_client.go
  pkg/client/v1beta1/informers/externalversions/factory.go
  pkg/client/v1beta1/informers/externalversions/generic.go
  pkg/client/v1beta1/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/v1beta1/informers/externalversions/mattermost/interface.go
  pkg/client/v1beta1/informers/externalversions/mattermost/v1beta1/interface.go
  pkg/client/v1beta1/informers/externalversions/mattermost/v1beta1/mattermost.go
  pkg/client/v1beta1/listers/mattermost/v1beta1/expansion_generated.go
  pkg/client/v1beta1/listers/mattermost/v1beta1/mattermost.go
Labels: 3: Reviews Complete, release-note-none

#203 Resource generation for Operator beta spec
  pkg/components/minio/minio.go
  pkg/components/mysql/mysql.go
  pkg/database/database.go
  pkg/mattermost/database_external.go
  pkg/mattermost/database_external_test.go
  pkg/mattermost/database_mysql.go
  pkg/mattermost/database_mysql_test.go
  pkg/mattermost/env_var.go
  pkg/mattermost/file_store.go
  pkg/mattermost/file_store_test.go
  pkg/mattermost/helpers.go
  pkg/mattermost/helpers_test.go
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_v1beta.go
  pkg/mattermost/mattermost_v1beta_test.go
  pkg/mattermost/util.go
Labels: 2: Dev Review, release-note-none

#204 add image pull policy option to spec
  apis/mattermost/v1alpha1/clusterinstallation_types.go
  apis/mattermost/v1alpha1/clusterinstallation_utils.go
  apis/mattermost/v1alpha1/zz_generated.openapi.go
  config/crd/bases/mattermost.com_clusterinstallations.yaml
  pkg/mattermost/mattermost.go
Labels: 3: Reviews Complete, release-note
