Repository mattermost/mattermost-operator, pull requests merged in 2020-09, with the labels that each got.

#175 Refactor ClusterInstallation state logic
  go.mod
  go.sum
  pkg/controller/clusterinstallation/controller.go
  pkg/controller/clusterinstallation/create_resources.go
  pkg/controller/clusterinstallation/mattermost.go
  pkg/controller/clusterinstallation/minio.go
  pkg/controller/clusterinstallation/utils.go
  pkg/mattermost/helpers.go
  pkg/mattermost/helpers_test.go
  pkg/mattermost/mattermost.go
  vendor/github.com/banzaicloud/k8s-objectmatcher/patch/annotation.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/modules.txt
Labels: 3: Reviews Complete, kind/cleanup, release-note

#176 remove field from CRD that is not used anymore
  deploy/crds/mattermost.com_clusterinstallations_crd.yaml
  pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
  pkg/apis/mattermost/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go
Labels: 3: Reviews Complete, kind/cleanup, release-note-none

#178 Add Mattermost database read replica configuration
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_test.go
Labels: 3: Reviews Complete, kind/feature, release-note

#181 prepare for the new release
  version/version.go
Labels: 3: Reviews Complete, kind/cleanup, release-note-none

#182 Bump default Mattermost version to 5.27.0
  pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Labels: 2: Dev Review, kind/cleanup, release-note
