Repository mattermost/mattermost-operator, pull requests merged in 2020-07, with the labels that each got.

#156 Add external database init check
  go.sum
  pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
  pkg/controller/clusterinstallation/controller.go
  pkg/controller/clusterinstallation/controller_test.go
  pkg/controller/clusterinstallation/create_resources.go
  pkg/controller/clusterinstallation/mattermost.go
  pkg/controller/clusterinstallation/mattermost_test.go
  pkg/controller/clusterinstallation/mysql.go
  pkg/controller/clusterinstallation/postgresql.go
  pkg/database/database.go
  pkg/database/database_test.go
Labels: 2: Infra Review, kind/feature, release-note

#158 Cleanup Mattermost app resource constructors
  deploy/crds/mattermost.com_clusterinstallations_crd.yaml
  go.mod
  go.sum
  pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
  pkg/controller/clusterinstallation/mattermost.go
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/mattermost/constants.go
  pkg/mattermost/helpers.go
  pkg/mattermost/helpers_test.go
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_test.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/modules.txt
Labels: 3: Reviews Complete, kind/cleanup, release-note

#159 fix broken master
  go.mod
  go.sum
  hack/tools.go
  vendor/modules.txt
Labels: release-note-none

#161 Use database secret values with MySQL operator connections
  go.mod
  go.sum
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/mattermost/mattermost.go
  vendor/modules.txt
Labels: 3: Reviews Complete, kind/feature, release-note

#162 remove dependencies from tools.go and make a little bit better
  .circleci/config.yml
  .gitignore
  Makefile
  go.mod
  go.sum
  hack/tools.go
  scripts/go_install.sh
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/vendor.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/modules.txt
Labels: 2: Infra Review, kind/cleanup, release-note-none

#160 probes: add startup probe to take care for the starting up process
  Makefile
  deploy/crds/mattermost.com_clusterinstallations_crd.yaml
  pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
  pkg/apis/mattermost/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go
  pkg/mattermost/helpers.go
  pkg/mattermost/helpers_test.go
  pkg/mattermost/mattermost.go
Labels: 3: Reviews Complete, kind/feature, release-note

#163 Bump default Mattermost version to 5.25.0
  pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Labels: 2: Infra Review, release-note-none

#164 add option to use digest id instead of tag
  pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Labels: 3: Reviews Complete, kind/feature, release-note

#165 bump version to prepare the 1.6.0 release before the v1beta1
  version/version.go
Labels: 3: Reviews Complete, kind/cleanup, release-note-none

#166 add check modules to check outdated dependencies
  .circleci/config.yml
  .gitignore
  Makefile
Labels: 2: Infra Review, kind/cleanup, release-note

#167 [GH-123] Treat Size as an write-only field
  README.md
  deploy/crds/mattermost.com_clusterinstallations_crd.yaml
  docs/examples/full.yaml
  pkg/apis/mattermost/v1alpha1/clusterinstallation_sizes.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
  pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go
Labels: 2: Dev Review, release-note-none

#169 probes: remove startup probe because 1.17 this is not enabled and was causing reconcile infinite loop
  pkg/controller/clusterinstallation/create_resources.go
  pkg/mattermost/helpers.go
  pkg/mattermost/helpers_test.go
  pkg/mattermost/mattermost.go
Labels: 2: Infra Review, kind/bug, release-note
