Repository mattermost/mattermost-operator, pull requests merged in 2020-04, with the labels that each got.

#137 Bump internal version variable
  version/version.go
Labels: 2: Ready to Merge

#136 Mm 23681 - Adding support for custom resource labels
  deploy/crds/mattermost.com_clusterinstallations_crd.yaml
  pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
  pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
  pkg/apis/mattermost/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go
  pkg/controller/clusterinstallation/controller_test.go
  pkg/controller/clusterinstallation/utils.go
Labels: 2: Ready to Merge

#139 github/template: add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3: Reviews Complete, kind/documentation, release-note-none

#141 add job to notify releases into a Mattermost channel
  .github/workflows/notify-release.yml
Labels: 3: Reviews Complete, kind/documentation, kind/feature, release-note-none
