Repository mattermost/mattermost-operator, pull requests merged in 2020-11, with the labels that each got.

#189 MM-29717 - Add ability to limit number of installation in Reconciling state
  config/manager/manager.yaml
  controllers/mattermost/clusterinstallation/controller.go
  controllers/mattermost/clusterinstallation/controller_test.go
  controllers/mattermost/clusterinstallation/mattermost_test.go
  controllers/mattermost/clusterinstallation/utils.go
  controllers/mattermost/mattermostrestoredb/controller.go
  docs/mattermost-operator/mattermost-operator.yaml
  go.mod
  go.sum
  main.go
  vendor/github.com/vrischmann/envconfig/.travis.yml
  vendor/github.com/vrischmann/envconfig/LICENSE
  vendor/github.com/vrischmann/envconfig/README.md
  vendor/github.com/vrischmann/envconfig/doc.go
  vendor/github.com/vrischmann/envconfig/envconfig.go
  vendor/github.com/vrischmann/envconfig/go.mod
  vendor/github.com/vrischmann/envconfig/go.sum
  vendor/github.com/vrischmann/envconfig/slice.go
  vendor/modules.txt
Labels: 2: Infra Review, release-note

#193 Regenerate manifests
  config/crd/bases/mattermost.com_clusterinstallations.yaml
  config/crd/bases/mattermost.com_mattermostrestoredbs.yaml
  docs/mattermost-operator/mattermost-operator.yaml
Labels: release-note-none

#194 Add Job that initializes MM database
  apis/mattermost/v1alpha1/zz_generated.openapi.go
  config/rbac/role.yaml
  controllers/mattermost/clusterinstallation/bluegreen.go
  controllers/mattermost/clusterinstallation/canary.go
  controllers/mattermost/clusterinstallation/controller.go
  controllers/mattermost/clusterinstallation/create_resources.go
  controllers/mattermost/clusterinstallation/mattermost.go
  controllers/mattermost/clusterinstallation/mattermost_test.go
  docs/mattermost-operator/mattermost-operator.yaml
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_test.go
Labels: 3: Reviews Complete, release-note

#195 Add cloud specific sizes for 10 and 100 users
  apis/mattermost/v1alpha1/clusterinstallation_sizes.go
Labels: release-note

#196 MM-30448 - Support Init containers waiting for Postgres readiness
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_test.go
Labels: 3: Reviews Complete, kind/feature, release-note

#198 Pushing the version to 1.11.0
  version/version.go
Labels: release-note-none

#197 Add v1beta1 of the Mattermost operator spec
  PROJECT
  apis/mattermost/v1beta1/groupversion_info.go
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/mattermost.mattermost.com_mattermosts.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_mattermosts.yaml
  config/crd/patches/webhook_in_mattermosts.yaml
  config/rbac/mattermost_editor_role.yaml
  config/rbac/mattermost_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/mattermost_v1beta1_mattermost.yaml
  main.go
Labels: 3: Reviews Complete, kind/design, release-note

#199 MM-30712 - Restart update job if image changed
  apis/mattermost/v1alpha1/clusterinstallation_utils.go
  controllers/mattermost/clusterinstallation/mattermost.go
  controllers/mattermost/clusterinstallation/mattermost_test.go
  pkg/mattermost/mattermost_test.go
Labels: 3: Reviews Complete, release-note
