Repository mattermost/mattermost-operator, pull requests merged in 2021-02, with the labels that each got.

#214 Refactor mattermost ingress resource generation
  controllers/mattermost/mattermost/mattermost.go
  pkg/mattermost/mattermost_v1beta.go
  pkg/mattermost/mattermost_v1beta_test.go
Labels: 2: Dev Review, 2: Infra Review, kind/cleanup, release-note

#218 Update dependencies
  go.mod
  go.sum
  pkg/resources/create_resources.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/doc.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/register.go
  vendor/k8s.io/client-go/metadata/interface.go
  vendor/k8s.io/client-go/metadata/metadata.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/metadata_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: 2: Dev Review, 2: Infra Review, kind/cleanup, release-note

#219 MM-32818 - Set default pathType in Ingress
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_test.go
  pkg/mattermost/mattermost_v1beta.go
  pkg/mattermost/mattermost_v1beta_test.go
Labels: 3: Reviews Complete, release-note

#217 MM-32704 - Improve workflow with Kind
  Makefile
  README.md
  scripts/install-mysql-minio.sh
  scripts/kind-config.yaml
  scripts/setup_kind.sh
  test/e2e.sh
  test/e2e_local.sh
  test/setup_test.sh
Labels: 3: Reviews Complete, release-note-none

#222 MM-32666 - Add issue template for Mattermost Operator repository
  .github/ISSUE_TEMPLATE.md
Labels: release-note-none
