Repository mattermost/mattermost-operator, pull requests merged in 2021-08, with the labels that each got.

#238 Set Observed Generation status value
  apis/mattermost/v1beta1/mattermost_types.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  controllers/mattermost/mattermost/controller.go
  controllers/mattermost/mattermost/health_check.go
Labels: 2: Dev Review, kind/feature, release-note

#236 MM-32705 - Document running Operator locally for development
  README.md
Labels: 3: Reviews Complete, release-note-none

#239 Bump default mattermost version to 5.37.1
  apis/mattermost/v1alpha1/clusterinstallation_utils.go
  apis/mattermost/v1beta1/mattermost_utils.go
Labels: 3: Reviews Complete, kind/cleanup, release-note

#240 Prepare Operator manifests for new release
  docs/mattermost-operator/mattermost-operator.yaml
Labels: 3: Reviews Complete, release-note

#241 Always update Mattermost status if there are any differences
  Makefile
  controllers/mattermost/mattermost/controller.go
  controllers/mattermost/mattermost/controller_test.go
  controllers/mattermost/mattermost/utils.go
Labels: 3: Reviews Complete, kind/bug, release-note
