Repository mattermost/mattermost-operator, pull requests merged in 2021-12, with the labels that each got.

#267 Add `appProtocol` to Service Creation
  pkg/mattermost/mattermost_v1beta.go
  pkg/mattermost/mattermost_v1beta_test.go
Labels: 2: Dev Review, release-note

#264 Add possibility to specify resource patch
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/patch_apply.go
  apis/mattermost/v1beta1/patch_apply_test.go
  apis/mattermost/v1beta1/testdata/deploy_patch.json
  apis/mattermost/v1beta1/testdata/port_patch.json
  apis/mattermost/v1beta1/testdata/service_patch.json
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  apis/mattermost/v1beta1/zz_generated.openapi.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  controllers/mattermost/mattermost/controller.go
  controllers/mattermost/mattermost/controller_test.go
  controllers/mattermost/mattermost/health_check.go
  controllers/mattermost/mattermost/mattermost.go
  controllers/mattermost/mattermost/mattermost_test.go
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/feature, release-note

#268 Prepare manifest for new release
  docs/mattermost-operator/mattermost-operator.yaml
Labels: release-note-none
