Repository mattermost/mattermost-operator, pull requests merged in 2021-01, with the labels that each got.

#206 MM-31335 - Implement migration from ClusterInstallation to Mattermost
  apis/mattermost/v1alpha1/clusterinstallation_types.go
  apis/mattermost/v1alpha1/clusterinstallation_utils.go
  apis/mattermost/v1alpha1/zz_generated.deepcopy.go
  apis/mattermost/v1alpha1/zz_generated.openapi.go
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/mattermost_utils.go
  apis/mattermost/v1beta1/zz_generated.openapi.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  config/crd/bases/mattermost.com_clusterinstallations.yaml
  controllers/mattermost/clusterinstallation/controller.go
  controllers/mattermost/clusterinstallation/controller_test.go
  controllers/mattermost/clusterinstallation/conversion.go
  controllers/mattermost/clusterinstallation/conversion_test.go
  controllers/mattermost/clusterinstallation/migration.go
  controllers/mattermost/mattermost/file_store.go
  pkg/client/v1beta1/clientset/versioned/clientset.go
  pkg/client/v1beta1/clientset/versioned/fake/clientset_generated.go
  pkg/client/v1beta1/clientset/versioned/fake/register.go
  pkg/client/v1beta1/clientset/versioned/scheme/register.go
  pkg/client/v1beta1/informers/externalversions/mattermost/v1beta1/mattermost.go
  pkg/mattermost/mattermost_v1beta.go
  pkg/mattermost/mattermost_v1beta_test.go
Labels: 2: Dev Review, 2: Infra Review, release-note

#207 Cleanup Operator Beta manifest
  config/crd/bases/mattermost.mattermost.com_mattermosts.yaml
  config/crd/kustomization.yaml
  config/samples/installation.mattermost.com_v1beta1_mattermost.yaml
  config/samples/kustomization.yaml
  docs/mattermost-operator/mattermost-operator.yaml
Labels: release-note

#208 MM-31880 - Decrease the requests of small cloud cluster installations
  apis/mattermost/v1alpha1/clusterinstallation_sizes.go
Labels: 2: Dev Review, 2: Infra Review, release-note-none

#211 README fix on release process
  README.md
Labels: release-note-none

#210 MM-31750 - Use new Mattermost resource in end to end tests
  test/e2e/main_test.go
  test/e2e/mattermost_test.go
  test/e2e/utils.go
Labels: release-note-none

#209 MM-31748 - Add documentation on how to migrate to Mattermost CR
  README.md
  docs/migration.md
Labels: 2: Dev Review, kind/documentation, release-note

#212 MM-29613 - Set MM_FILESETTINGS_AMAZONS3SSL to true when using external file store
  pkg/mattermost/env_var.go
  pkg/mattermost/file_store.go
  pkg/mattermost/file_store_test.go
  pkg/mattermost/mattermost_v1beta_test.go
Labels: kind/feature, release-note

#213 Add examples for new Mattermost CR
  docs/examples/mattermost_full.yaml
  docs/examples/mattermost_mysql_minio_operators_small.yaml
  docs/examples/mattermost_simple_anywhere.yaml
  docs/examples/mattermost_simple_aws_azure.yaml
Labels: kind/documentation, release-note
