Repository mattermost/mattermost-operator, pull requests merged in 2022-07, with the labels that each got.

#288 Don't return errors waiting for job update
  controllers/mattermost/mattermost/controller.go
  controllers/mattermost/mattermost/mattermost.go
  controllers/mattermost/mattermost/mattermost_test.go
Labels: 3: Reviews Complete, kind/cleanup, release-note

#292 Introduce the 'ready' state to signal instance readiness
  apis/mattermost/v1beta1/mattermost_types.go
  controllers/mattermost/mattermost/controller.go
  controllers/mattermost/mattermost/controller_test.go
  controllers/mattermost/mattermost/health_check.go
Labels: release-note

#296 Fix reconciliation of Installation with 0 replicas
  controllers/mattermost/mattermost/controller.go
  controllers/mattermost/mattermost/controller_test.go
  controllers/mattermost/mattermost/health_check.go
Labels: 3: Reviews Complete, kind/bug, release-note

#295 Fixed changing service type between headless service and LoadBalancer
  controllers/mattermost/mattermost/mattermost.go
  controllers/mattermost/mattermost/mattermost_test.go
  pkg/mattermost/mattermost_v1beta.go
  pkg/resources/create_resources.go
Labels: 3: Reviews Complete, kind/feature, release-note
