Repository mattermost/mattermost-operator, pull requests merged in 2022-12, with the labels that each got.

#294 feat(ingress): aws alb
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/mattermost_utils.go
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  apis/mattermost/v1beta1/zz_generated.openapi.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  config/rbac/role.yaml
  controllers/mattermost/mattermost/mattermost.go
  controllers/mattermost/mattermost/mattermost_test.go
  pkg/mattermost/mattermost.go
  pkg/mattermost/mattermost_v1beta.go
  pkg/resources/create_resources.go
Labels: 3: Reviews Complete, kind/feature, release-note

#317 Bump default Mattermost version
  apis/mattermost/v1alpha1/clusterinstallation_utils.go
  apis/mattermost/v1beta1/mattermost_utils.go
  test/constants.go
Labels: 3: Reviews Complete, release-note-none, kind/chore

#319 Add external volume filestore type
  apis/mattermost/v1beta1/file_store_util.go
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  config/manager/kustomization.yaml
  controllers/mattermost/mattermost/file_store.go
  controllers/mattermost/mattermost/mattermost_test.go
  docs/mattermost-operator/mattermost-operator.yaml
  pkg/mattermost/file_store.go
  pkg/mattermost/file_store_test.go
Labels: 2: Dev Review, kind/feature, release-note

#318 feat(ingress): custom annotations for alb ingress
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/mattermost_utils.go
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  controllers/mattermost/mattermost/mattermost_test.go
  docs/examples/mattermost_full_aws_alb.yaml
  pkg/mattermost/mattermost_v1beta.go
Labels: 3: Reviews Complete, release-note, kind/chore

#320 feat(filestore): use service account for s3 api calls
  apis/mattermost/v1beta1/mattermost_types.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  controllers/mattermost/mattermost/controller_test.go
  controllers/mattermost/mattermost/file_store.go
  controllers/mattermost/mattermost/mattermost.go
  controllers/mattermost/mattermost/mattermost_test.go
  docs/mattermost-operator/mattermost-operator.yaml
  pkg/mattermost/env_var.go
  pkg/mattermost/file_store.go
  pkg/mattermost/file_store_test.go
Labels: 2: Dev Review, kind/feature, release-note

#328 Use custom GOPATH in github actions
  .github/workflows/ci.yml
Labels: kind/feature, release-note-none

#330 Kind version from sha256 instead of tag
  Makefile
  scripts/kind-config-amd64.yaml
  scripts/kind-config-arm64.yaml
  scripts/kind-config.yaml
  scripts/setup_kind.sh
Labels: 3: Reviews Complete, release-note-none, kind/chore
