Repository mattermost/mattermost-operator, pull requests merged in 2022-01, with the labels that each got.

#252 New readme intro and logo
  README.md
Labels: 2: Dev Review, release-note-none

#265 Add ability for custom DNSConfig and DNSPolicy
  .circleci/config.yml
  apis/mattermost/v1alpha1/clusterinstallation_utils.go
  apis/mattermost/v1alpha1/zz_generated.deepcopy.go
  apis/mattermost/v1alpha1/zz_generated.openapi.go
  apis/mattermost/v1beta1/mattermost_test.go
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  apis/mattermost/v1beta1/zz_generated.openapi.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  pkg/mattermost/mattermost_v1beta.go
  test/constants.go
Labels: 3: Reviews Complete, kind/feature, release-note

#272 Do not log Mattermost spec on update
  controllers/mattermost/clusterinstallation/controller.go
  controllers/mattermost/mattermost/controller.go
Labels: 3: Reviews Complete, release-note, kind/chore
