Repository mattermost/mattermost-operator, pull requests merged in 2022-09, with the labels that each got.

#300 Avoid rewriting command for injected sidecars
  pkg/resources/update_job.go
Labels: release-note

#302 Update podTemplate to be a pointer
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/mattermost_utils.go
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  apis/mattermost/v1beta1/zz_generated.openapi.go
  pkg/mattermost/mattermost_v1beta.go
  pkg/mattermost/mattermost_v1beta_test.go
Labels: 3: Reviews Complete, kind/cleanup, release-note

#301 Add support for labels/annotations and disabling on update job
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  apis/mattermost/v1beta1/zz_generated.openapi.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  controllers/mattermost/clusterinstallation/mattermost.go
  controllers/mattermost/mattermost/mattermost.go
  controllers/mattermost/mattermost/mattermost_test.go
  pkg/resources/update_job.go
Labels: 2: Dev Review, release-note

#303 [GH-216] Add e2e ingress tests
  test/e2e-external/apply_resource.go
  test/e2e-external/ingress_test.go
  test/e2e/instance.go
  test/e2e_local.sh
Labels: 3: Reviews Complete, release-note-none

#304 Fix replicas status reported in Mattermost CR
  controllers/mattermost/clusterinstallation/controller_test.go
  controllers/mattermost/clusterinstallation/utils.go
  controllers/mattermost/mattermost/controller.go
  controllers/mattermost/mattermost/controller_test.go
  controllers/mattermost/mattermost/health_check.go
  pkg/mattermost/healthcheck/health_check.go
Labels: 3: Reviews Complete, release-note

#309 e2e test for version upgrade
  test/e2e-external/external_db_filestore_test.go
  test/e2e/utils.go
Labels: 2: Dev Review, release-note

#310 update MattermostVersion in test
  apis/mattermost/v1beta1/mattermost_test.go
  test/constants.go
Labels: 3: Reviews Complete, release-note

#311 e2e test for size & resource update
  test/e2e-external/size_test.go
  test/e2e-external/utils.go
Labels: 3: Reviews Complete, release-note

#312 Prepare manifest for new release
  docs/mattermost-operator/mattermost-operator.yaml
Labels: release-note-none
