Repository mattermost/mattermost-operator, pull requests merged in 2023-02, with the labels that each got.

#335 [MM-49782] Allow configurable deployment revision history limit
  apis/mattermost/v1beta1/mattermost_types.go
  apis/mattermost/v1beta1/zz_generated.deepcopy.go
  apis/mattermost/v1beta1/zz_generated.openapi.go
  config/crd/bases/installation.mattermost.com_mattermosts.yaml
  pkg/mattermost/mattermost_v1beta.go
Labels: 3: Reviews Complete, kind/feature, release-note

#338 Update dev size resource values
  apis/mattermost/v1alpha1/clusterinstallation_sizes.go
Labels: 3: Reviews Complete, kind/cleanup, release-note

#341 Hardcode e2e golang image to v1.19.4
  test/e2e.sh
Labels: 2: Dev Review, release-note, kind/chore

#344 Include `ready` installations in reconcile limit check
  controllers/mattermost/mattermost/controller.go
  controllers/mattermost/mattermost/controller_test.go
Labels: 2: Dev Review, kind/bug, release-note
